println("Int16 的存储空间大小是: ", sizeof(Int16), "个字节")
println("Int8  的存储空间大小是: ", sizeof(Int8), "个字节")
println("Int32 的存储空间大小是: ", sizeof(Int32), "个字节")
println("Int64 的存储空间大小是: ", sizeof(Int64), "个字节")
println("Int128 的存储空间大小是: ", sizeof(Int128), "个字节")
println()
println("UInt16 的存储空间大小是: ", sizeof(UInt16), "个字节")
println("UInt64 的存储空间大小是: ", sizeof(UInt64), "个字节")
println("UInt128 的存储空间大小是: ", sizeof(UInt128), "个字节")
